version: '3.8'
services:
  PostgreSQL:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sentronics-api:
    build:
      context: .
    restart: on-failure
    image: 'sentronics-api.jar'
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - PostgreSQL
    volumes:
      - ./data:/data
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:${DATABASE_TYPE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${JPA_HIBERNATE_DDL_AUTO}

volumes:
  postgres-data:
